== [[RecordAsMp3]]Record SID as MP3 by Command Line

You can record SID as MP3 by command line using the following minimum options:

[source,subs="attributes+"]
----
java -jar jsidplay2-console-{version}.jar # <1>
--audio LIVE_MP3 # <2>
---- 
<1> Launch command-line version
<2> Record audio output as MP3 (and listen live on Soundcard)

Example:
[source,subs="attributes+"]
----
Turrican_2-The_Final_Fight.sid --startSong 4 --single true --audio LIVE_MP3
---- 

In this example we record the tune Turrican_2-The_Final_Fight.sid starting with song 4.
Since the SID file contains multiple songs and we want to record only song 4, we use
the option named single.

The result is a file called Turrican-04.mp3, this is because the sub-song 4 will be part of the filename.

TIP: If you prefer not to listen the tune while recording, simply use option:
[source,subs="attributes+"]
----
--audio MP3 <1>
----
<1> Record as MP3 but we don't want to listen using our soundcard meanwhile. Beside that record time is much faster.

TIP: If you prefer to record only certain voices of a tune you are able to mute voices this way:
[source,subs="attributes+"]
----
--muteVoice1 true<1>
----
<1> Mute voice 1 (of the main SID). See usage to mute other voices as well.

TIP: If you want only to record a specific time range of the SID:
[source,subs="attributes+"]
----
--startTime 01:26  --defaultLength 01:30 <1>
----
<1> Start song at 1 minute and 26 seconds and record for one and a half minute.

TIP: You can change the quality settings of MP3 recordings this way:
[source,subs="attributes+"]
----
--cbr 160 <1>
--vbr true --vbrQuality 0 <2>
----
<1> Bitrate in kbps (-1=auto, 32 40 48 56 64 80 96 112 128 160 192 224 256 320)
<2> or alternatively use variable bitrate and highest quality (0=best, 5=medium, 9=worst)

== [[RecordingTool]]Do mass recordings by command Line
You can record the full HVSC (all SIDs) as MP3 using parallel processing.
[source,subs="attributes+"]
----
recordingtool.sh # <1>
--audio MP3 # <2>
--maxThreads <maxThreads> # <3>
--destinationDirectory <recordingDirectory # <4>
--hvsc <pathToHVSC> # <5>
<rootDirectory> # <6>
----
<1> Launch command-line version
<2> Output format.
<3> Maximum number of recordings done in parallel.
<4> Optional output directory. Sub-directories will be created automatically to get the same folder structure like <rootDirectory>. If parameter is missing, all recordings are created in the same folder like the SIDs).
<5> HVSC directory to read the song length database (SLDB). That means the file in sub-folder DOCUMENTS/STIL.txt will be read.
<6> Main parameter: Directory to create recordings for. If you want to record full HVSC please use HVSC directory the same like above (<pathToHVSC>).

Example:
[source,subs="attributes+"]
----
recordingtool.sh --audio MP3 --maxThreads 8 --hvsc /media/nas1/Ken/C64/C64Music --destinationDirectory /home/ken/out /media/nas1/Ken/C64/C64Music
----
TIP: You can use even more parameters (change output format, mute voices, etc. just to name a few). Please refer to the usage messages.
