== SIDBlaster

*Credits*

SIDBlaster is an USB device to use the famous soundchip of the Commodore 64 home computer of the 1980's,
the MOS6581 and its successor CSG8085.

SIDBlaster is available as a Tic-Tac edition created by Andreas Schumm
and based on SIDBlaster-USB by Davey (Das Phantom).

It is available at the following web-site: link:http://crazy-midi.de[http://crazy-midi.de^]

The SIDBlaster library has been created by Stein Pedersen and ported to Linux and MacOSX by Ken Händel.

The purpose of the SIDBlaster library is to access your SIDBlaster device using your software like JSIDPlay2.

This guide is for you to use that library.

=== User Instructions

==== Use JSIDPlay2 with SIDBlaster on MacOSX

JSIDPlay2 requires Java, therefore install java first.
I recommend to install it from the folowing site:
link:https://adoptium.net[https://adoptium.net^]

Choose "OpenJDT11" and "Hotspot"

Then download and install it on your machine.

You can verify this by opening the command line and type
[source,subs="attributes+"]
----
java -version
----

Now you can install JSIDPlay2 from my web-site and extract it to the Downloads folder.

[source,subs="attributes+"]
----
cd /Users/<name>/Downloads/{artifactId}-{version}-mac
"./jsidplay2.sh"			 # <1>
----
<1> Before you launch JSIDPlay2 you must be sure, that you connected your SIDBlaster device with your machine.
*Note:* It can be necessary to change the path to java inside that script to that of your installation.


*Note:* hot-plugging SIDBlaster devices is not supported. Therefore everytime you connect a device, you must restart JSIDPlay2, unfortunately.

Inside JSIDPlay2 on your tool bar you can now change from Emulation to SIDBlaster

This will again most likely raise a security alert.
Therefore, open "Security and Privacy Settings" from the system settings dialog.
Unlock Settings with your password to be able to change one of these settings.
Now, click allow for the SIDBlaster library, that was blocked before.
Please restart JSIDPlay2, now.

In JSIDPlay2 the tool bar should display SIDBlaster instead of emulation now.
Please check, that your console view and terminal does not show any error messages regarding the SIDBlaster library.
Then we are fine until here.

Then we can let JSIDPlay2 auto-detect all connected SIDBlaster devices,
therefore click on the SIDBlaster settings in the tool bar to expand all available SIDBlaster settings.
There is a magic wand to click. At the end it adds all detected SIDBlaster devices to your configuration.

All SIDBlaster devices will display a serial number and a chip type, which is still unknown (it is not stored on the hardware device, yet).
Therefore select the suitable SID chip model installed on your SIDBlaster device.
Now we are ready to test is using the Play button near the serial number to test each detected device.
Does it play? Then we are fine.

==== Use JSIDPlay2 with SIDBlaster on Windows

JSIDPlay2 requires Java, therefore install java first.
I recommend to install it from the folowing site:
link:https://adoptium.net[https://adoptium.net^]

Choose "OpenJDT11" and "Hotspot"

Then download and install it on your machine.

You can verify this by opening the command line and type
[source,subs="attributes+"]
----
java -version
----

Now you can install JSIDPlay2 from my web-site and extract it to the Downloads folder.

In the Windows Explorer please go to the following location:

"/Users/<name>/Downloads/{artifactId}-{version}-win/{artifactId}-{version}-win"

Now plug-in your SIDBlaster devices and start the executable "{artifactId}-{version}.exe" from the Explorer.

Inside JSIDPlay2 on your tool bar you can now change from Emulation to SIDBlaster

*Note:* hot-plugging SIDBlaster devices is not supported. Therefore everytime you connect a device, you must restart JSIDPlay2, unfortunately.

Inside JSIDPlay2 on your tool bar you can now change from Emulation to SIDBlaster

Please check, that your console view and terminal does not show any error messages regarding the SIDBlaster library.
Then we are fine until here.

Then we can let JSIDPlay2 auto-detect all connected SIDBlaster devices,
therefore click on the SIDBlaster settings in the tool bar to expand all available SIDBlaster settings.
There is a magic wand to click. At the end it adds all detected SIDBlaster devices to your configuration.

All SIDBlaster devices will display a serial number and a chip type, which is still unknown (it is not stored on the hardware device, yet).
Therefore select the suitable SID chip model installed on your SIDBlaster device.
Now we are ready to test is using the Play button near the serial number to test each detected device.
Does it play? Then we are fine.

==== Use JSIDPlay2 with SIDBlaster on Linux

JSIDPlay2 requires Java, therefore install java first.
I recommend to install it from the folowing site:
link:https://adoptium.net[https://adoptium.net^]

Choose "OpenJDT11" and "Hotspot"

Then download and install it on your machine.

[source,subs="attributes+"]
----
cd /home/<name>/Downloads
tar xzvf OpenJDK11U-jdk_64_linux_hotspot_11.0.11_9.tar.gz
cd jdk-11.0.11+9/bin
./java -version
----

Now you can install JSIDPlay2 from my web-site and extract it to the Downloads folder.

*Note:* Because the ftd2xx library interferes with a built-in linux kernel module we have to install a script to unload the kernel module
whenever a SIDBlaster card is plugged-in, therefore:

[source,subs="attributes+"]
----
sudo vi /etc/udev/rules.d/91-sidblaster.rules
ACTION=="add", ATTRS{idVendor}=="0403", ATTRS{idProduct}=="6001", MODE="0666",  RUN+="/bin/sh -c 'rmmod ftdi_sio && rmmod usbserial'"
sudo udevadm control --reload-rules && udevadm trigger
----

[source,subs="attributes+"]
----
unzip /home/<name>/Downloads/{artifactId}-{version}-linux.zip
cd /home/<name>/Downloads/{artifactId}-{version}-linux
"./jsidplay2.sh"	 # <1>
----
<1> Before you launch JSIDPlay2 you must be sure, that you connected your SIDBlaster device with your machine.

*Note:* It can be necessary to change the path to java inside that script to that of your installation.

*Note:* hot-plugging SIDBlaster devices is not supported. Therefore everytime you connect a device, you must restart JSIDPlay2, unfortunately.

Inside JSIDPlay2 on your tool bar you can now change from Emulation to SIDBlaster

Please check, that your console view and terminal does not show any error messages regarding the SIDBlaster library.
Then we are fine until here.

Then we can let JSIDPlay2 auto-detect all connected SIDBlaster devices,
therefore click on the SIDBlaster settings in the tool bar to expand all available SIDBlaster settings.
There is a magic wand to click. At the end it adds all detected SIDBlaster devices to your configuration.

All SIDBlaster devices will display a serial number and a chip type, which is still unknown (it is not stored on the hardware device, yet).
Therefore select the suitable SID chip model installed on your SIDBlaster device.
Now we are ready to test is using the Play button near the serial number to test each detected device.
Does it play? Then we are fine.

=== SIDBlaster tool

The purpose of that tool is to communicate with the device for administrative reasons
or to prepare the permanent usage inside JSIDPlay2 or other projects.

JSIDPlay2 ships with a sidblaster tool to change device settings,
that is namely the serial number and the SID chip type.
You can permanently store the SID chip type to be auto-detected by JSIDPlay2.

[source,subs="attributes+"]
----
cd /Users/<name>/Downloads/{artifactId}-{version}-*
"./sidblaster-tool.sh"										 # <1>
"./sidblaster-tool.sh" -c INFO								 # <2>
"./sidblaster-tool.sh" -c SET_SID_TYPE -d 0 -t SIDTYPE_6581	 # <3>
"./sidblaster-tool.sh" -c SET_SERIAL -d 0 -s A12B34C56D		 # <4>
----
<1> Display usage
<2> List detected devices
<3> Example to set SID chip type
<4> Example to set serial number

*Note:* Windows users execute sidblastertool-{version}.exe on the command line, instead!
